web_MVC/Models/ChartViewModel.cs
using System.Collections.Generic;

namespace web_MVC.Models
{
    public class ChartViewModel
    {
        public List<string> Names { get; set; }
        public string SelectedOption { get; set; }
        public string SelectedChartType { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public List<string> SelectedNames { get; set; }

        public ChartViewModel()
        {
            Names = new List<string>
            {
                "TOOL1", "TOOL2", "TOOL3", "TOOL5", "TOOL6", "TOOL7", "TOOL8", "TOOL9", "TOOL10",
                "TOOL11", "TOOL12_", "TOOL13", "TOOL14", "TOOL15", "TOOL16", "TOOL17", "TOOL18",
                "TOOL19", "TOOL20", "AIRCOM", "TOTAL"
            };
            SelectedNames = new List<string>();
        }
    }

  
}

web_MVC/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using web_MVC.Models;

namespace web_MVC.Controllers
{
    public class ChartController : Controller
    {
        private readonly string connectionString = "server=127.0.0.1;database=di_schemas;user id=root;port=3306;password=123456;AllowLoadLocalInfile=true;";

        public IActionResult Index()
        {
            var model = new ChartViewModel
            {
                StartDate = DateTime.Today.ToString("yyyy-MM-dd"),
                EndDate = DateTime.Today.ToString("yyyy-MM-dd")
            };
            return View(model);
        }

     

        [HttpPost]
        public IActionResult LoadData(ChartViewModel model)
        {
            if (string.IsNullOrEmpty(model.StartDate) || string.IsNullOrEmpty(model.EndDate) || model.SelectedNames == null || model.SelectedNames.Count == 0)
            {
                ViewBag.ErrorMessage = "Please provide all required inputs.";
                return View("Index", model);
            }

            if (!DateTime.TryParse(model.StartDate, out DateTime dateS) || !DateTime.TryParse(model.EndDate, out DateTime dateE))
            {
                ViewBag.ErrorMessage = "Please enter valid dates.";
                return View("Index", model);
            }

            if (dateS > dateE)
            {
                ViewBag.ErrorMessage = "Start date cannot be after end date.";
                return View("Index", model);
            }

            var chartData = GetData(model.SelectedOption, dateS, dateE, model.SelectedNames);
            return Json(chartData);
        }

        private List<ChartDataModel> GetData(string option, DateTime dateS, DateTime dateE, List<string> names)
        {
            var chartData = new List<ChartDataModel>();

            using (var con = new MySqlConnection(connectionString))
            {
                con.Open();

                foreach (var name in names)
                {
                    Console.WriteLine("@@@@@@"+name);
                    if (option == "power")
                    {
                        chartData.AddRange(GetPowerData(con, dateS, dateE, name));
                    }
                    else if (option == "energy")
                    {
                        chartData.AddRange(GetEnergyData(con, dateS, dateE, name));
                    }
                    else if (option == "Mix")
                    {
                        chartData.AddRange(GetPowerData(con, dateS, dateE, name));
                        chartData.AddRange(GetEnergyData(con, dateS, dateE, name));
                    }
                }
            }

            return chartData;
        }

        private List<ChartDataModel> GetPowerData(MySqlConnection con, DateTime dateS, DateTime dateE, string name)
        {
            var powerData = new List<ChartDataModel>();
            var query = new MySqlCommand($@"
                SELECT DISTINCT
                    t1.Name as Name,
                    t1.Value AS max_value,
                    t1.Datetime 
                FROM 
                    di_schemas.powerdata_dmpower t1
                JOIN (
                    SELECT DISTINCT
                        DATE(Datetime) AS date,
                        MAX(CAST(Value AS DOUBLE)) AS max_value
                    FROM 
                        di_schemas.powerdata_dmpower
                    WHERE 
                        Datetime BETWEEN @DateS AND @DateE
                        AND Name = @Name
                    GROUP BY 
                        DATE(Datetime)
                ) t2 ON DATE(t1.Datetime) = t2.date 
                   AND t1.Value = t2.max_value
                GROUP BY
                    t2.date
                ORDER BY 
                    t1.Datetime;", con);

            query.Parameters.AddWithValue("@DateS", dateS.ToString("yyyy-MM-dd") + " 00:00:00");
            query.Parameters.AddWithValue("@DateE", dateE.ToString("yyyy-MM-dd") + " 23:59:59");
            query.Parameters.AddWithValue("@Name", name + "_Demand_KW");

            using (var reader = query.ExecuteReader())
            {
                while (reader.Read())
                {
                    powerData.Add(new ChartDataModel
                    {
                        Name = reader["Name"].ToString(),
                        Value = Convert.ToDouble(reader["max_value"]),
                        Datetime = reader["Datetime"].ToString()
                    });
                }
            }

            return powerData;
        }

        private List<ChartDataModel> GetEnergyData(MySqlConnection con, DateTime dateS, DateTime dateE, string name)
        {
            var energyData = new List<ChartDataModel>();
            var query2 = new MySqlCommand($@"
                SELECT 
                    Name,
                    DATE(Datetime) AS Datetime,
                    MAX(Value) - MIN(Value) AS difference
                FROM 
                    di_schemas.powerdata_energy
                WHERE
                    Datetime BETWEEN @DateS AND @DateE AND Name = @Name
                GROUP BY 
                    DATE(Datetime);", con);

            query2.Parameters.AddWithValue("@DateS", dateS.ToString("yyyy-MM-dd")+"00:00:00");
            query2.Parameters.AddWithValue("@DateE", dateE.ToString("yyyy-MM-dd")+"23:59:00");
            query2.Parameters.AddWithValue("@Name", name + "_KWH");

            using (var reader = query2.ExecuteReader())
            {
                while (reader.Read())
                {
                    energyData.Add(new ChartDataModel
                    {
                        Name = reader["Name"].ToString(),
                        Value = Convert.ToDouble(reader["difference"]),
                        Datetime = reader["Datetime"].ToString()
                    });
                }
            }

            return energyData;
        }
    }
}

web_MVC/Controllers/ChartViewController.cs
using System;
using System.Collections.Generic;
using System.Threading;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using web_MVC.Models;
using System.Windows;
using System.Net.Http;
using System.Threading.Tasks;
using System.Configuration;

namespace web_MVC.Controllers
{ 
    public class ChartViewController : Controller
    {
        private readonly string connectionString = "server=127.0.0.1;database=di_schemas;user id=root;port=3306;password=123456;AllowLoadLocalInfile=true;";
        private static Timer _timer;
        private static List<ChartDataModel> _cachedPowerData = new List<ChartDataModel>();
        private static List<ChartDataModel> _cachedEnergyData = new List<ChartDataModel>();
        private static int currentMinute = 0; // 初始化為當天的第一分鐘
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfiguration _configuration;


        public ChartViewController(IHttpClientFactory httpClientFactory, IConfiguration configuration)
        {
            _httpClientFactory = httpClientFactory;
            _configuration = configuration;


        }
  
     

        public IActionResult Index()
        {
            return View();
        }

        

          public async Task<IActionResult> getPowerData(int currentMin)
        {
            var result = await FetchPowerData(currentMin);

            if (result is ContentResult contentResult)
            {
                return Content(contentResult.Content, "application/json");
            }
            else if (result is ObjectResult objectResult)
            {
                return Json(objectResult.Value);
            }
            else
            {
                return StatusCode(500, "Failed to fetch power data.");
            }
        }
        [HttpGet("GetPowerData")]
     
        public async Task<IActionResult> FetchPowerData(int currentMin)
        {
            var client = _httpClientFactory.CreateClient();
            var apiUrl = $"{_configuration["ApiUrl"]}/api/Api/GetPowerData?minuteOfDay={currentMin}";

            var response = await client.GetAsync(apiUrl);
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                return Content(data, "application/json");
            }

            return StatusCode((int)response.StatusCode, await response.Content.ReadAsStringAsync());
        }

      public async Task<IActionResult> getEnergyData(int currentMin)
        {
            var result = await FetchEnergyData(currentMin);

            if (result is ContentResult contentResult)
            {
                return Content(contentResult.Content, "application/json");
            }
            else if (result is ObjectResult objectResult)
            {
                return Json(objectResult.Value);
            }
            else
            {
                return StatusCode(500, "Failed to fetch energy data.");
            }
        }
        [HttpGet("GetEnergyData")]
  
        public async Task<IActionResult> FetchEnergyData(int currentMin)
        {
            var client = _httpClientFactory.CreateClient();
            var apiUrl = $"{_configuration["ApiUrl"]}/api/Api/GetEnergyData?minuteOfDay={currentMin}";

            var response = await client.GetAsync(apiUrl);
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                return Content(data, "application/json");
            }

            return StatusCode((int)response.StatusCode, await response.Content.ReadAsStringAsync());
        }

    }
}

web_MVC/Views/Chart/index.cshtml
@model web_MVC.Models.ChartViewModel

@{
    ViewData["Title"] = "Chart Data";
    Layout = "_Layout";
}
<html>



<head>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.0/font/bootstrap-icons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" type="text/css">
</head>

<div class="title">
    <i class="bi bi-chevron-double-right" onclick="sideBarClicked()" id="sidebarDiv"></i>
    <h2>PowerGlow Interactive Data Query System</h2>
</div>


<body>
  

    <form id="chartForm" asp-action="LoadData" asp-controller="Chart" method="post" class="formStyle">
        <div class="optionDiv">
            <label for="SelectedOption">Option:</label>
            <select asp-for="SelectedOption" asp-items="@(new SelectList(new List<string> { "power", "energy", "Mix" }))">
                <option value="">Select Option</option>
            </select>
        </div>
        <div class="optionDiv">
            <label for="SelectedChartType">Chart Type:</label>
            <select asp-for="SelectedChartType" asp-items="@(new SelectList(new List<string> { "line", "bar", "Mix" }))">
                <option value="">Select Type</option>
            </select>
        </div>

        <div class="optionDiv">
            <label for="StartDate">Start Date:</label>
            <input asp-for="StartDate" type="date" />
        </div>
        <div class="optionDiv">
            <label for="EndDate">End Date:</label>
            <input asp-for="EndDate" type="date" />
        </div>
        <div class="optionDiv">
            <label for="SelectedNames">Names:</label>
            <select asp-for="SelectedNames" asp-items="@(new MultiSelectList(Model.Names))" multiple="multiple"></select>
        </div>
        <button type="submit">Load Data</button>
        <button type="button" onclick="location.href='@Url.Action("Index", "ChartView")'">Go to Chart View</button>

    </form>




    <div id="chartContainer" class="chartStyle">
        <!-- Chart will be rendered here -->
    </div>
    <div class="tableStyle">
        <div id="powerTableContainer">
            <h3>Power Data</h3>
            <table id="powerDataTable" border="1" class="powerTable">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Value</th>
                        <th>Datetime</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Power data rows will be appended here -->
                </tbody>
            </table>
        </div>

        <div id="energyTableContainer">
            <h3>Energy Data</h3>
            <table id="energyDataTable" border="1" class="energyTable">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Value</th>
                        <th>Datetime</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Energy data rows will be appended here -->
                </tbody>
            </table>
        </div>
    </div>



</body>
    
            
        

    
</html>

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.3/dist/chart.umd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@3.0.0/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
    <script>
        
        function sideBarClicked() {
                var sideBar = document.querySelector('.sidebar');
                if (sideBar) {
                    sidebar.classList.toggle('hidden');
                    console.log("hidden!!!!!");
                }
                else {
                    console.log("?????????!!!!!");
                }
            }
        $(document).ready(function () {
            
            $('#chartForm').submit(function (e) {
                e.preventDefault();

                $.ajax({
                    url: '@Url.Action("LoadData", "Chart")',
                    type: 'POST',
                    data: $(this).serialize(),
                    success: function (data) {
                        console.log('Data received from server:', data);
                        if (data && Array.isArray(data)) {
                            console.log("Names in data: ", data.map(item => item.name));
                            renderChart(data, $('#SelectedChartType').val());
                            renderPowerTable(data);
                            renderEnergyTable(data);
                        } else {
                            console.error('Unexpected data format received:', data);
                        }
                    },
                    error: function (error) {
                        console.error('Error during AJAX request:', error);
                    }
                });
            });

            function renderChart(data, selectedChartType) {
                $('#chartContainer').empty();
                var labels = [];
                var datasets = [];
                var minDate = null;
                var maxDate = null;

                if (!data || !Array.isArray(data)) {
                    console.error('Invalid data:', data);
                    return;
                }

                var powerData = data.filter(item => item.name && item.name.includes('_Demand_KW'));
                var energyData = data.filter(item => item.name && item.name.includes('_KWH'));

                console.log('Power Data:', powerData);
                console.log('Energy Data:', energyData);

                powerData.forEach(function (item) {
                    var chartType = selectedChartType;
                    if (selectedChartType == 'Mix') chartType = 'line';
                    console.log("power type: " + chartType);
                    var itemDate = new Date(item.datetime);
                    if (!minDate || itemDate < minDate) minDate = itemDate;
                    if (!maxDate || itemDate > maxDate) maxDate = itemDate;

                    if (!labels.includes(itemDate)) {
                        labels.push(itemDate);
                    }

                    var dataset = datasets.find(d => d.label === item.name);
                    if (!dataset) {
                        dataset = {
                            label: item.name,
                            data: [],
                            borderColor: getRandomColor(),
                            backgroundColor: getRandomColor(),
                            fill: false,
                            pointBackgroundColor: [],
                            pointBorderColor: [],
                            pointRadius: [],
                            type: chartType
                        };
                        datasets.push(dataset);
                    }
                    dataset.data.push({ x: itemDate, y: item.value });
                    console.log("itemDate: " + itemDate + " value: " + item.value);
                    dataset.pointBackgroundColor.push('rgba(22, 22, 0, 0.1)');
                    dataset.pointBorderColor.push('rgba(10, 10, 100, 1)');
                    dataset.pointRadius.push(5);
                });

                energyData.forEach(function (item) {
                    var chartType = selectedChartType;
                    if (selectedChartType == "Mix") chartType = 'bar';
                    console.log("energy type: " + chartType);
                    var itemDate = new Date(item.datetime);
                    var dataset = datasets.find(d => d.label === item.name);
                    if (!dataset) {
                        dataset = {
                            label: item.name,
                            data: [],
                            borderColor: 'rgba(255, 99, 132, 1)',
                            backgroundColor: getRandomColor(),
                            fill: false,
                            yAxisID: 'y-axis-2',
                            type: chartType,
                            pointBackgroundColor: [],
                            pointBorderColor: [],
                            pointRadius: []
                        };
                        datasets.push(dataset);
                    }
                    dataset.data.push({ x: itemDate, y: item.value });
                    dataset.pointBackgroundColor.push('rgba(255, 99, 132, 0.5)');
                    dataset.pointBorderColor.push('rgba(255, 99, 132, 1)');
                    dataset.pointRadius.push(5);
                });

                var ctx = document.createElement('canvas');
                $('#chartContainer').append(ctx);

                new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: labels,
                        datasets: datasets
                    },
                    options: {
                        scales: {
                            x: {
                                type: 'time',
                                time: {
                                    unit: 'day',
                                    displayFormats: {
                                        day: 'yyyy-MM-dd HH:mm:ss'
                                    },
                                    tooltipFormat: 'yyyy-MM-dd HH:mm:ss'
                                },
                                min: minDate,
                                max: maxDate,
                                beginAtZero: true
                            },
                            y: {
                                beginAtZero: true,
                                position: 'left'
                            },
                            'y-axis-2': {
                                type: 'linear',
                                position: 'right',
                                beginAtZero: true,
                                grid: {
                                    drawOnChartArea: false
                                }
                            }
                        },
                        plugins: {
                            tooltip: {
                                callbacks: {
                                    label: function (context) {
                                        var label = context.dataset.label || '';
                                        if (label) {
                                            label += ': ';
                                        }
                                        label += context.raw.y;
                                        return label;
                                    }
                                }
                            }
                        }
                    }
                });
            }

            function renderPowerTable(data) {
                var powerTableBody = $('#powerDataTable tbody');
                powerTableBody.empty();

                var powerData = data.filter(item => item.name && item.name.includes('_Demand_KW'));
                console.log('Power Table Data:', powerData);
                powerData.forEach(function (item) {
                    var row = '<tr>' +
                        '<td>' + item.name + '</td>' +
                        '<td>' + item.value + '</td>' +
                        '<td>' + new Date(item.datetime).toLocaleString() + '</td>' +
                        '</tr>';
                    powerTableBody.append(row);
                });
            }

            function renderEnergyTable(data) {
                var energyTableBody = $('#energyDataTable tbody');
                energyTableBody.empty();

                var energyData = data.filter(item => item.name && item.name.includes('_KWH'));
                console.log('Energy Table Data:', energyData);
                energyData.forEach(function (item) {
                    var row = '<tr>' +
                        '<td>' + item.name + '</td>' +
                        '<td>' + item.value + '</td>' +
                        '<td>' + new Date(item.datetime).toLocaleString() + '</td>' +
                        '</tr>';
                    energyTableBody.append(row);
                });
            }

            function getRandomColor() {
                var letters = '0123456789ABCDEF';
                var color = '#';
                for (var i = 0; i < 6; i++) {
                    color += letters[Math.floor(Math.random() * 16)];
                }
                return color;
            }

         
        });
    </script>
}